version: '3'

services:
    client:
        image: mlops-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
        - 8501:8501
    mongo:
        image: mongo

    server:
        image: mlops-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
        - 8000:8000